### ISSUE TITLE
No defaultPackage.x86_64-linux?

### ISSUE THREAD

**Issue by rydnr** [virchau13/automatic1111-webui-nix#4]
Hi,

Blindly following the README instructions yields (in my laptop):
```
error: getting status of '/nix/store/jr0dgqz1ffl4lyw1fzihaj9q0c0g9bq8-source/flake.nix': No such file or directory
```
After running `nix flake update`, I get this error now:
```
error: flake 'git+file:///[...]/automatic1111-webui-nix' does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
```

I'm running NixOS 22.11 (configured using flakes), Linux kernel 5.15.103.

Any ideas?

**Comment by virchau13** [comment]
If you run `git add .` in the A1111 repository _before_`nix develop`, does it work?

**Comment by plul** [comment]
@virchau13 I think there's two issues:

- add `git add .` or similar to README instructions
- change to say `nix develop` not `nix shell` in:

> nix shell # or `nix-shell` if you're not using flakes.
